# Set the distro to Ubuntu 20.04 LTS
dist: focal

before_install:
  - chmod 777 ./scripts/setup.sh && sudo ./scripts/setup.sh

# Run unit tests scripts
# Test independent stuff first
script:
  - chmod 777 ./scripts/independent_tests.sh && ./scripts/independent_tests.sh
  - chmod 777 ./scripts/4589_pa1_test.sh && ./scripts/4589_pa1_test.sh
  - chmod 777 ./deployment/linux_setup/cse4568.sh && sudo ./deployment/linux_setup/cse4568.sh
  - chmod 777 ./deployment/entry.sh && sudo ./deployment/entry.sh --no-GUI