# Set the distro to Ubuntu 20.04 LTS
dist: focal

before_install:
  - chmod 777 ./travis_scripts/setup.sh && sudo ./travis_scripts/setup.sh

# Run unit tests scripts
# Test independent stuff first
script:
  - chmod 777 ./travis_scripts/independent_tests.sh && ./travis_scripts/independent_tests.sh
  - chmod 777 ./travis_scripts/4589_pa1_test.sh && ./travis_scripts/4589_pa1_test.sh
